print("hello, World!") 
print("yo")
print('Hii, Esther')
print("The itsy bitsy spider \nclimbed up the waterspout.")
print()
print("Down came the rain and \nwashed the spider out.")
print("The itsy bitsy spider" , "climbed up" , "the waterspout.")
print("My name is", "Esther.", end=" ")
print("Esther Girly.")
print("My name is Esther.", "Esther Girly.")
print("My name is ", end="")
print("Esstargirly")
print("My name", "is", "Esther", "Girly", sep="")
print("My", "name", "is", sep="_", end="*")
print("Monty", "Python.", sep="*", end="*\n")

print("Programming","Essentials","in", sep="***", end="...")
print("Python")

print("My\nname\nis\nBond.", end=" ")
print("James Bond.")

print("fish ", " chips", sep="&")